# URL de conexão (substitua 'meu_banco' pelo nome do seu banco criado no pgAdmin)
spring.datasource.url=jdbc:postgresql://localhost:5432/bibliocanto

# Usuário e Senha
spring.datasource.username=postgres
spring.datasource.password=estudo99

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
